//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pactica123.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Vales_Resguardos
    {
        public int id_detalle_vale_resguardo { get; set; }
        public Nullable<int> id_resguardo { get; set; }
        public Nullable<int> id_inventario { get; set; }
        public string cantidad { get; set; }
    
        public virtual Numero_Inventario Numero_Inventario { get; set; }
        public virtual Tabla_Resguardos Tabla_Resguardos { get; set; }
    }
}
