//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pactica123.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Vale_Prestamo
    {
        public int id_detalle_vale_prestamo { get; set; }
        public Nullable<int> id_prestamo { get; set; }
        public Nullable<int> id_inventario { get; set; }
        public string cantidad { get; set; }
    
        public virtual Vale_De_Prestamo Vale_De_Prestamo { get; set; }
    }
}
