//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pactica123.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InventarioEntities : DbContext
    {
        public InventarioEntities()
            : base("name=InventarioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adscripcion> Adscripcion { get; set; }
        public virtual DbSet<Detalle_Vale_Prestamo> Detalle_Vale_Prestamo { get; set; }
        public virtual DbSet<Detalle_Vales_Resguardos> Detalle_Vales_Resguardos { get; set; }
        public virtual DbSet<Fuentes_Financiamiento> Fuentes_Financiamiento { get; set; }
        public virtual DbSet<Numero_Inventario> Numero_Inventario { get; set; }
        public virtual DbSet<Personas> Personas { get; set; }
        public virtual DbSet<Tabla_Articulos> Tabla_Articulos { get; set; }
        public virtual DbSet<Tabla_Resguardos> Tabla_Resguardos { get; set; }
        public virtual DbSet<Tabla_Tipos_Puesto> Tabla_Tipos_Puesto { get; set; }
        public virtual DbSet<Vale_De_Prestamo> Vale_De_Prestamo { get; set; }
    }
}
