//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pactica123.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tabla_Resguardos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tabla_Resguardos()
        {
            this.Detalle_Vales_Resguardos = new HashSet<Detalle_Vales_Resguardos>();
        }
    
        public int id_resguardo { get; set; }
        public Nullable<int> id_persona { get; set; }
        public Nullable<System.DateTime> fecha_entrega { get; set; }
        public Nullable<int> id_Autoriza { get; set; }
        public Nullable<int> id_Realiza { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_Vales_Resguardos> Detalle_Vales_Resguardos { get; set; }
        public virtual Personas Personas { get; set; }
    }
}
