//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pactica123.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tabla_Articulos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tabla_Articulos()
        {
            this.Numero_Inventario = new HashSet<Numero_Inventario>();
        }
    
        public int id_articulo { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> cantidad { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public string numero_serie { get; set; }
        public Nullable<decimal> costo_adquisicion { get; set; }
        public Nullable<System.DateTime> fecha_adquisicion { get; set; }
        public Nullable<int> id_fuente_financiamiento { get; set; }
    
        public virtual Fuentes_Financiamiento Fuentes_Financiamiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Numero_Inventario> Numero_Inventario { get; set; }
    }
}
