//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pactica123.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vale_De_Prestamo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vale_De_Prestamo()
        {
            this.Detalle_Vale_Prestamo = new HashSet<Detalle_Vale_Prestamo>();
        }
    
        public int id_prestamo { get; set; }
        public Nullable<System.DateTime> Fecha_Emision { get; set; }
        public string Lugar { get; set; }
        public Nullable<System.DateTime> Fecha_Devolucion { get; set; }
        public string Descripcion_Articulo { get; set; }
        public string Objetivo { get; set; }
        public string NombreEntrega { get; set; }
        public string NombreSolicitante { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_Vale_Prestamo> Detalle_Vale_Prestamo { get; set; }
    }
}
